version: '3.8'

services:
  shoppinglist:
    build:
      context: .
      dockerfile: Dockerfile
    image: shoppinglist:latest
    container_name: shoppinglist
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX=1000
    volumes:
      - shopping_list_data:/usr/src/app/data
    pull_policy: build

volumes:
  shopping_list_data:
