version: '3.8'

services:
  shopping-list:
    build: .
    image: shopping-list:latest
    container_name: shopping-list
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - shopping_list_data:/usr/src/app/data
    pull_policy: build

volumes:
  shopping_list_data:
